services:
  athena_app:
    container_name: athena_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/data/app
    ports:
      - "8080:8080"
    networks:
      - athena
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: athena_db
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: athena
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - athena
    restart: unless-stopped

  pgadmin:
    container_name: athena_db_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - athena
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  athena:
    driver: bridge

volumes:
  app:
  postgres:
  pgadmin:
