apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena-db
  namespace: athena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: athena-db-secret
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: athena-db-secret
                  key: DATABASE_PASSWORD
            - name: POSTGRES_DB
              value: athena
          volumeMounts:
            - name: postgres-data
              mountPath: /data/postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
